version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-node-vue
    ports:
      - '80:8080'
    volumes:
      - ./app:/app
      - /app/node_modules
    working_dir: /app
    command: /bin/sh -c "npm run serve"