version: '3.7'
services:
  frontend:
    image: node:14.5.0-alpine
    ports:
      - '80:8080'
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    working_dir: /app
    command: /bin/sh -c "npm run serve"